name: pr-check

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          # output changed services as json
          list-tags: 'json'
          filters: |
            catalog: 'backend/catalog/**'
            orders: 'backend/orders/**'
            inventory: 'backend/inventory/**'
            payments: 'backend/payments/**'
            notifications: 'backend/notifications/**'

  test:
    needs: detect-changes
    # run if changes detected
    if: ${{ needs.detect-changes.outputs.services != '[]' && needs.detect-changes.outputs.services != '' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build dynamic matrix
        service: ${{ fromJSON(needs.detect-changes.outputs.services) }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          
      - name: build and test
        run: |
          cd backend/${{ matrix.service }}
          chmod +x gradlew
          ./gradlew build
          ./gradlew test
